# 使用官方 Python 镜像作为基础镜像
FROM python:3.9

# 设置工作目录
WORKDIR /app

# 复制当前目录下的所有文件到容器的 /app 目录下
COPY . /app

# 安装依赖项
RUN pip install --no-cache-dir -r requirements.txt

# 暴露应用程序需要的端口
EXPOSE 9000
EXPOSE 5001

# 复制启动脚本到容器中
COPY start.sh /app/start.sh

# 设置启动脚本可执行权限
RUN chmod +x /app/start.sh

# 启动应用程序
CMD ["/app/start.sh"]
